"""add_category_trending_phrase_table

Revision ID: 094727eeafe8
Revises: a1b2c3d4e5f6
Create Date: 2025-06-24 02:51:39.060794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094727eeafe8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_trending_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('phrase_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_trending_phrases_category'), 'category_trending_phrases', ['category'], unique=False)
    op.create_index(op.f('ix_category_trending_phrases_date'), 'category_trending_phrases', ['date'], unique=False)
    op.create_index(op.f('ix_category_trending_phrases_id'), 'category_trending_phrases', ['id'], unique=False)
    op.add_column('articles', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('articles', 'category')
    op.drop_index(op.f('ix_category_trending_phrases_id'), table_name='category_trending_phrases')
    op.drop_index(op.f('ix_category_trending_phrases_date'), table_name='category_trending_phrases')
    op.drop_index(op.f('ix_category_trending_phrases_category'), table_name='category_trending_phrases')
    op.drop_table('category_trending_phrases')
    # ### end Alembic commands ###
