"""Add trending phrases table

Revision ID: e54222444f09
Revises: f8a404f506a4
Create Date: 2025-05-29 17:02:16.241069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54222444f09'
down_revision: Union[str, None] = 'f8a404f506a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('phrase_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_phrases_date'), 'trending_phrases', ['date'], unique=False)
    op.create_index(op.f('ix_trending_phrases_id'), 'trending_phrases', ['id'], unique=False)
    
    # Add new columns to articles table
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False, server_default='news'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('published_date')
        batch_op.drop_column('url')
        
    op.drop_index(op.f('ix_trending_phrases_id'), table_name='trending_phrases')
    op.drop_index(op.f('ix_trending_phrases_date'), table_name='trending_phrases')
    op.drop_table('trending_phrases')
    # ### end Alembic commands ###
